"""
Paciolus Disposable Email Blocker
Sprint 57: Verified-Account-Only Model

Blocks registration attempts from known disposable/temporary email domains.
This helps prevent abuse and ensures users provide legitimate contact emails.
"""

# Common disposable email domains (200+ domains)
# Sources: Various public lists of known temporary email services
DISPOSABLE_EMAIL_DOMAINS = frozenset([
    # Major disposable email services
    "10minutemail.com",
    "10minutemail.net",
    "10minutemail.org",
    "10minmail.com",
    "20minutemail.com",
    "33mail.com",
    "emailondeck.com",
    "fakeinbox.com",
    "fakemailgenerator.com",
    "getairmail.com",
    "getnada.com",
    "guerrillamail.com",
    "guerrillamail.org",
    "guerrillamail.net",
    "guerrillamail.biz",
    "guerrillamail.de",
    "guerrillamail.info",
    "guerrillamailblock.com",
    "mailinator.com",
    "mailinator.net",
    "mailinator.org",
    "mailinator2.com",
    "maildrop.cc",
    "mailnesia.com",
    "mailcatch.com",
    "mailexpire.com",
    "mailforspam.com",
    "mailfree.ga",
    "mailmoat.com",
    "mailnator.com",
    "mailnull.com",
    "mailsac.com",
    "mailslurp.com",
    "mailtemp.org",
    "meltmail.com",
    "mintemail.com",
    "mohmal.com",
    "mytemp.email",
    "mytrashmail.com",
    "sharklasers.com",
    "spambox.us",
    "spamgourmet.com",
    "spamspot.com",
    "tempail.com",
    "tempemail.net",
    "tempmailaddress.com",
    "tempmail.com",
    "tempmail.io",
    "tempmail.net",
    "tempmailbox.com",
    "tempr.email",
    "throwaway.email",
    "throwawayemail.com",
    "throwawaymail.com",
    "trashmail.com",
    "trashmail.net",
    "trashmail.org",
    "yopmail.com",
    "yopmail.fr",
    "yopmail.net",
    "dispostable.com",
    "disposable.email",
    "discard.email",
    "discardmail.com",
    "emailfake.com",
    "fakemail.net",
    "fakebox.org",
    "inboxalias.com",
    "incognitomail.com",
    "jetable.org",
    "kasmail.com",
    "kukumail.com",
    "laafd.com",
    "mailcatch.com",
    "mailchop.com",
    "maildx.com",
    "mailhz.me",
    "mailimate.com",
    "mailismagic.com",
    "mailn8r.com",
    "mailquack.com",
    "mailrock.biz",
    "mailseal.de",
    "mailshell.com",
    "mailzilla.com",
    "nomail.xl.cx",
    "nospam.ze.tc",
    "notmailinator.com",
    "nowmymail.com",
    "obobbo.com",
    "oneoffemail.com",
    "otherinbox.com",
    "owlpic.com",
    "pjjkp.com",
    "politikerclub.de",
    "poofy.org",
    "proxymail.eu",
    "putthisinyourspamdatabase.com",
    "quickinbox.com",
    "rejectmail.com",
    "rppkn.com",
    "safersignup.de",
    "safetymail.info",
    "sandelf.de",
    "sendspamhere.com",
    "shiftmail.com",
    "smellfear.com",
    "snakemail.com",
    "sneakemail.com",
    "sofort-mail.de",
    "sogetthis.com",
    "soodonims.com",
    "spam4.me",
    "spamavert.com",
    "spambob.com",
    "spambog.com",
    "spambog.de",
    "spamcon.org",
    "spamday.com",
    "spamex.com",
    "spamfree24.com",
    "spamfree24.de",
    "spamfree24.eu",
    "spamfree24.info",
    "spamfree24.net",
    "spamfree24.org",
    "spamhole.com",
    "spamify.com",
    "spaminator.de",
    "spamkill.info",
    "spaml.com",
    "spaml.de",
    "spammotel.com",
    "spamobox.com",
    "spamoff.de",
    "spamslicer.com",
    "spamstack.net",
    "spamthis.co.uk",
    "spamthisplease.com",
    "spamtrail.com",
    "speed.1s.fr",
    "spoofmail.de",
    "squizzy.de",
    "sry.li",
    "stuffmail.de",
    "supergreatmail.com",
    "supermailer.jp",
    "superstachel.de",
    "suremail.info",
    "teleworm.com",
    "teleworm.us",
    "temp-mail.org",
    "temp-mail.ru",
    "tempinbox.co.uk",
    "tempinbox.com",
    "tempmail2.com",
    "tempomail.fr",
    "temporarily.de",
    "temporaryemail.net",
    "temporaryforwarding.com",
    "temporaryinbox.com",
    "temporarymailaddress.com",
    "thanksnospam.info",
    "thankyou2010.com",
    "thisisnotmyrealemail.com",
    "throam.com",
    "throwam.com",
    "tilien.com",
    "tmail.ws",
    "tmailinator.com",
    "toiea.com",
    "trash2009.com",
    "trash2010.com",
    "trash2011.com",
    "trashdevil.com",
    "trashdevil.de",
    "trashemail.de",
    "trashmailer.com",
    "trashymail.com",
    "trashymail.net",
    "turual.com",
    "twinmail.de",
    "tyldd.com",
    "uggsrock.com",
    "upliftnow.com",
    "uplipht.com",
    "venompen.com",
    "veryrealemail.com",
    "viditag.com",
    "viewcastmedia.com",
    "viewcastmedia.net",
    "viewcastmedia.org",
    "wegwerfadresse.de",
    "wegwerfemail.de",
    "wegwerfmail.de",
    "wegwerfmail.info",
    "wegwerfmail.net",
    "wegwerfmail.org",
    "wetrainbayarea.com",
    "wetrainbayarea.org",
    "whopy.com",
    "willhackforfood.biz",
    "willselfdestruct.com",
    "winemaven.info",
    "wronghead.com",
    "wuzup.net",
    "wuzupmail.net",
    "xents.com",
    "xmaily.com",
    "xoxy.net",
    "yapped.net",
    "yep.it",
    "yogamaven.com",
    "ypmail.webarnak.fr.eu.org",
    "zippymail.info",
    "zoemail.com",
    "zoemail.net",
    "zoemail.org",
    # Additional popular services
    "burnermail.io",
    "emkei.cz",
    "anonymmail.net",
    "anobox.ru",
    "antireg.ru",
    "drdrb.com",
    "e4ward.com",
    "emailthe.net",
    "email-fake.com",
    "fakeinformation.com",
    "imstations.com",
    "inboxbear.com",
    "inboxkitten.com",
    "jetable.com",
    "mail-temp.com",
    "mailtemp.info",
    "moakt.com",
    "rcpt.at",
    "receivemail.com",
    "spamwtf.com",
    "tempemail.com",
    "tempemail.co",
    "tempsky.com",
    "tmpmail.net",
    "tmpmail.org",
    "zemail.me",
])


def is_disposable_email(email: str) -> bool:
    """
    Check if an email address uses a known disposable email domain.

    Args:
        email: The email address to check

    Returns:
        True if the email domain is a known disposable service, False otherwise
    """
    if not email or "@" not in email:
        return False

    # Extract domain (case-insensitive)
    domain = email.lower().split("@")[-1].strip()

    # Check exact match
    if domain in DISPOSABLE_EMAIL_DOMAINS:
        return True

    # Check subdomain patterns (e.g., user.guerrillamail.com)
    parts = domain.split(".")
    if len(parts) > 2:
        # Check if the last two parts match a known domain
        parent_domain = ".".join(parts[-2:])
        if parent_domain in DISPOSABLE_EMAIL_DOMAINS:
            return True

    return False


def get_blocked_domain_count() -> int:
    """Return the count of blocked disposable email domains."""
    return len(DISPOSABLE_EMAIL_DOMAINS)
