"""initial_schema_users_clients_activity_diagnostics

Revision ID: ae18bcf1ba02
Revises: 
Create Date: 2026-02-08 11:35:20.598902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae18bcf1ba02'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diagnostic_summaries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('period_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('period_type', sa.Enum('MONTHLY', 'QUARTERLY', 'ANNUAL', name='periodtype'), nullable=True))
        batch_op.add_column(sa.Column('period_label', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('operating_expenses', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('net_profit_margin', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('operating_margin', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('return_on_assets', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('return_on_equity', sa.Float(), nullable=True))
        batch_op.create_index(batch_op.f('ix_diagnostic_summaries_period_date'), ['period_date'], unique=False)

    with op.batch_alter_table('email_verification_tokens', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.drop_index('ix_email_verification_tokens_token')
        batch_op.create_index(batch_op.f('ix_email_verification_tokens_token'), ['token'], unique=True)
        batch_op.create_index(batch_op.f('ix_email_verification_tokens_id'), ['id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('tier',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('FREE', 'PROFESSIONAL', 'ENTERPRISE', name='usertier'),
               nullable=False,
               existing_server_default=sa.text("'free'"))
        batch_op.create_index(batch_op.f('ix_users_email_verification_token'), ['email_verification_token'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email_verification_token'))
        batch_op.alter_column('tier',
               existing_type=sa.Enum('FREE', 'PROFESSIONAL', 'ENTERPRISE', name='usertier'),
               type_=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'free'"))

    with op.batch_alter_table('email_verification_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_verification_tokens_id'))
        batch_op.drop_index(batch_op.f('ix_email_verification_tokens_token'))
        batch_op.create_index('ix_email_verification_tokens_token', ['token'], unique=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('diagnostic_summaries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diagnostic_summaries_period_date'))
        batch_op.drop_column('return_on_equity')
        batch_op.drop_column('return_on_assets')
        batch_op.drop_column('operating_margin')
        batch_op.drop_column('net_profit_margin')
        batch_op.drop_column('operating_expenses')
        batch_op.drop_column('period_label')
        batch_op.drop_column('period_type')
        batch_op.drop_column('period_date')

    # ### end Alembic commands ###
