"""baseline: full schema as of v1.2.0

Revision ID: e2f21cb79a61
Revises: 
Create Date: 2026-02-12 18:03:43.565980

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e2f21cb79a61'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('tier', sa.Enum('FREE', 'PROFESSIONAL', 'ENTERPRISE', name='usertier'), nullable=False),
    sa.Column('email_verification_token', sa.String(length=64), nullable=True),
    sa.Column('email_verification_sent_at', sa.DateTime(), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('settings', sa.String(length=2000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_email_verification_token'), ['email_verification_token'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('filename_hash', sa.String(length=64), nullable=False),
    sa.Column('filename_display', sa.String(length=20), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('total_debits', sa.Float(), nullable=False),
    sa.Column('total_credits', sa.Float(), nullable=False),
    sa.Column('materiality_threshold', sa.Float(), nullable=False),
    sa.Column('was_balanced', sa.Boolean(), nullable=False),
    sa.Column('anomaly_count', sa.Integer(), nullable=True),
    sa.Column('material_count', sa.Integer(), nullable=True),
    sa.Column('immaterial_count', sa.Integer(), nullable=True),
    sa.Column('is_consolidated', sa.Boolean(), nullable=True),
    sa.Column('sheet_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_logs_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_logs_user_id'), ['user_id'], unique=False)

    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.Enum('TECHNOLOGY', 'HEALTHCARE', 'FINANCIAL_SERVICES', 'MANUFACTURING', 'RETAIL', 'PROFESSIONAL_SERVICES', 'REAL_ESTATE', 'CONSTRUCTION', 'HOSPITALITY', 'NONPROFIT', 'EDUCATION', 'OTHER', name='industry'), nullable=False),
    sa.Column('fiscal_year_end', sa.String(length=5), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('settings', sa.String(length=2000), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clients_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clients_user_id'), ['user_id'], unique=False)

    op.create_table('email_verification_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_verification_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_verification_tokens_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_verification_tokens_token'), ['token'], unique=True)
        batch_op.create_index(batch_op.f('ix_email_verification_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('diagnostic_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('period_date', sa.Date(), nullable=True),
    sa.Column('period_type', sa.Enum('MONTHLY', 'QUARTERLY', 'ANNUAL', name='periodtype'), nullable=True),
    sa.Column('period_label', sa.String(length=50), nullable=True),
    sa.Column('filename_hash', sa.String(length=64), nullable=True),
    sa.Column('filename_display', sa.String(length=20), nullable=True),
    sa.Column('total_assets', sa.Float(), nullable=True),
    sa.Column('current_assets', sa.Float(), nullable=True),
    sa.Column('inventory', sa.Float(), nullable=True),
    sa.Column('total_liabilities', sa.Float(), nullable=True),
    sa.Column('current_liabilities', sa.Float(), nullable=True),
    sa.Column('total_equity', sa.Float(), nullable=True),
    sa.Column('total_revenue', sa.Float(), nullable=True),
    sa.Column('cost_of_goods_sold', sa.Float(), nullable=True),
    sa.Column('total_expenses', sa.Float(), nullable=True),
    sa.Column('operating_expenses', sa.Float(), nullable=True),
    sa.Column('current_ratio', sa.Float(), nullable=True),
    sa.Column('quick_ratio', sa.Float(), nullable=True),
    sa.Column('debt_to_equity', sa.Float(), nullable=True),
    sa.Column('gross_margin', sa.Float(), nullable=True),
    sa.Column('net_profit_margin', sa.Float(), nullable=True),
    sa.Column('operating_margin', sa.Float(), nullable=True),
    sa.Column('return_on_assets', sa.Float(), nullable=True),
    sa.Column('return_on_equity', sa.Float(), nullable=True),
    sa.Column('total_debits', sa.Float(), nullable=True),
    sa.Column('total_credits', sa.Float(), nullable=True),
    sa.Column('was_balanced', sa.Boolean(), nullable=True),
    sa.Column('anomaly_count', sa.Integer(), nullable=True),
    sa.Column('materiality_threshold', sa.Float(), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('diagnostic_summaries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_diagnostic_summaries_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_diagnostic_summaries_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_diagnostic_summaries_period_date'), ['period_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_diagnostic_summaries_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_diagnostic_summaries_user_id'), ['user_id'], unique=False)

    op.create_table('engagements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', name='engagementstatus'), nullable=False),
    sa.Column('materiality_basis', sa.Enum('REVENUE', 'ASSETS', 'MANUAL', name='materialitybasis'), nullable=True),
    sa.Column('materiality_percentage', sa.Float(), nullable=True),
    sa.Column('materiality_amount', sa.Float(), nullable=True),
    sa.Column('performance_materiality_factor', sa.Float(), nullable=False),
    sa.Column('trivial_threshold_factor', sa.Float(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('engagements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_engagements_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_engagements_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_engagements_status'), ['status'], unique=False)

    op.create_table('tool_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('engagement_id', sa.Integer(), nullable=False),
    sa.Column('tool_name', sa.Enum('TRIAL_BALANCE', 'MULTI_PERIOD', 'JOURNAL_ENTRY_TESTING', 'AP_TESTING', 'BANK_RECONCILIATION', 'PAYROLL_TESTING', 'THREE_WAY_MATCH', 'REVENUE_TESTING', 'AR_AGING', 'FIXED_ASSET_TESTING', 'INVENTORY_TESTING', name='toolname'), nullable=False),
    sa.Column('run_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('COMPLETED', 'FAILED', name='toolrunstatus'), nullable=False),
    sa.Column('composite_score', sa.Float(), nullable=True),
    sa.Column('run_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tool_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tool_runs_engagement_id'), ['engagement_id'], unique=False)
        batch_op.create_index('ix_tool_runs_engagement_tool', ['engagement_id', 'tool_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_tool_runs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tool_runs_run_at'), ['run_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tool_runs_tool_name'), ['tool_name'], unique=False)

    op.create_table('follow_up_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('engagement_id', sa.Integer(), nullable=False),
    sa.Column('tool_run_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('tool_source', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='followupseverity'), nullable=False),
    sa.Column('disposition', sa.Enum('NOT_REVIEWED', 'INVESTIGATED_NO_ISSUE', 'INVESTIGATED_ADJUSTMENT_POSTED', 'INVESTIGATED_FURTHER_REVIEW', 'IMMATERIAL', name='followupdisposition'), nullable=False),
    sa.Column('auditor_notes', sa.Text(), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tool_run_id'], ['tool_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('follow_up_items', schema=None) as batch_op:
        batch_op.create_index('ix_follow_up_engagement_disposition', ['engagement_id', 'disposition'], unique=False)
        batch_op.create_index('ix_follow_up_engagement_severity', ['engagement_id', 'severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_follow_up_items_assigned_to'), ['assigned_to'], unique=False)
        batch_op.create_index(batch_op.f('ix_follow_up_items_disposition'), ['disposition'], unique=False)
        batch_op.create_index(batch_op.f('ix_follow_up_items_engagement_id'), ['engagement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_follow_up_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_follow_up_items_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_follow_up_items_tool_run_id'), ['tool_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_follow_up_items_tool_source'), ['tool_source'], unique=False)

    op.create_table('follow_up_item_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('follow_up_item_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('comment_text', sa.Text(), nullable=False),
    sa.Column('parent_comment_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['follow_up_item_id'], ['follow_up_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['follow_up_item_comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('follow_up_item_comments', schema=None) as batch_op:
        batch_op.create_index('ix_comment_item_parent', ['follow_up_item_id', 'parent_comment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_follow_up_item_comments_follow_up_item_id'), ['follow_up_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_follow_up_item_comments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_follow_up_item_comments_parent_comment_id'), ['parent_comment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_follow_up_item_comments_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follow_up_item_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_follow_up_item_comments_user_id'))
        batch_op.drop_index(batch_op.f('ix_follow_up_item_comments_parent_comment_id'))
        batch_op.drop_index(batch_op.f('ix_follow_up_item_comments_id'))
        batch_op.drop_index(batch_op.f('ix_follow_up_item_comments_follow_up_item_id'))
        batch_op.drop_index('ix_comment_item_parent')

    op.drop_table('follow_up_item_comments')
    with op.batch_alter_table('follow_up_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_follow_up_items_tool_source'))
        batch_op.drop_index(batch_op.f('ix_follow_up_items_tool_run_id'))
        batch_op.drop_index(batch_op.f('ix_follow_up_items_severity'))
        batch_op.drop_index(batch_op.f('ix_follow_up_items_id'))
        batch_op.drop_index(batch_op.f('ix_follow_up_items_engagement_id'))
        batch_op.drop_index(batch_op.f('ix_follow_up_items_disposition'))
        batch_op.drop_index(batch_op.f('ix_follow_up_items_assigned_to'))
        batch_op.drop_index('ix_follow_up_engagement_severity')
        batch_op.drop_index('ix_follow_up_engagement_disposition')

    op.drop_table('follow_up_items')
    with op.batch_alter_table('tool_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tool_runs_tool_name'))
        batch_op.drop_index(batch_op.f('ix_tool_runs_run_at'))
        batch_op.drop_index(batch_op.f('ix_tool_runs_id'))
        batch_op.drop_index('ix_tool_runs_engagement_tool')
        batch_op.drop_index(batch_op.f('ix_tool_runs_engagement_id'))

    op.drop_table('tool_runs')
    with op.batch_alter_table('engagements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_engagements_status'))
        batch_op.drop_index(batch_op.f('ix_engagements_id'))
        batch_op.drop_index(batch_op.f('ix_engagements_client_id'))

    op.drop_table('engagements')
    with op.batch_alter_table('diagnostic_summaries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diagnostic_summaries_user_id'))
        batch_op.drop_index(batch_op.f('ix_diagnostic_summaries_timestamp'))
        batch_op.drop_index(batch_op.f('ix_diagnostic_summaries_period_date'))
        batch_op.drop_index(batch_op.f('ix_diagnostic_summaries_id'))
        batch_op.drop_index(batch_op.f('ix_diagnostic_summaries_client_id'))

    op.drop_table('diagnostic_summaries')
    with op.batch_alter_table('email_verification_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_verification_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_email_verification_tokens_token'))
        batch_op.drop_index(batch_op.f('ix_email_verification_tokens_id'))

    op.drop_table('email_verification_tokens')
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clients_user_id'))
        batch_op.drop_index(batch_op.f('ix_clients_id'))

    op.drop_table('clients')
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_activity_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_activity_logs_id'))

    op.drop_table('activity_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email_verification_token'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
